name: Deploy Action

inputs:
  environment:
    required: true
    default: production

runs:
  using: composite

  steps:
    - shell: bash
      run: echo "Deploying to ${{ inputs.environment }}"
