name: Run Number Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Using Context
        run: echo "${{ github.run_number }}"

      - name: Using Environment Variable
        run: echo "$GITHUB_RUN_NUMBER"
