name: manual workflow
on: 
  workflow_dispatch:
    inputs: 
      environment:
        description: enter the environment name
        required: true
        default: "staging"
        type: choice
        options: 
          - staging 
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to production
        run: echo "deploy to ${{ inputs.environment }}"
