name: Self Hosted Runner Demo

on:
  workflow_dispatch:

jobs:
  self-hosted:
    runs-on: self-hosted

    steps:
      - name: Check hostname
        run: hostname

      - name: Check current user
        run: whoami

      - name: Check OS
        run: cat /etc/os-release
